services:
  - type: web
    name: gym-management-platform
    runtime: node
    plan: free
    region: oregon
    autoDeploy: true
    healthCheckPath: /
    buildCommand: npm run render-build
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 20.18.0
      - key: CI
        value: "false"
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        value: mongodb+srv://sadhanamarendra12_db_user:ArpitRai_12345@cluster0.b96elmj.mongodb.net/gym_management?retryWrites=true&w=majority&appName=Cluster0
      - key: MONGO_URI
        value: mongodb+srv://sadhanamarendra12_db_user:ArpitRai_12345@cluster0.b96elmj.mongodb.net/gym_management?retryWrites=true&w=majority&appName=Cluster0
      - key: EMAIL_USER
        value: sadhanamarendra12@gmail.com
      - key: EMAIL_PASS
        value: ooer pznc ydfz iwvr
