services:
  - type: web
    name: gym-management-platform
    env: node
    plan: free
    region: oregon
    buildCommand: npm run render-build
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 20.18.0
      - key: CI
        value: "false"
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: MONGO_URI
        sync: false
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASS
        sync: false

